on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Environment Variables
      shell: bash
      env:
        ENV: ${{ github.ref_name }}
      run: |
        if [ "$ENV" == "dev" ]; then
          echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}" >> $GITHUB_ENV
        elif [ "$ENV" == "qa" ]; then
          echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT_QA }}" >> $GITHUB_ENV
        elif [ "$ENV" == "main" ]; then
          echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT_MAIN }}" >> $GITHUB_ENV
        fi
    
    - name: Debug Snowflake Account
      run: |
        echo "::add-mask::$SNOWFLAKE_ACCOUNT"
        echo "SNOWFLAKE_ACCOUNT=$SNOWFLAKE_ACCOUNT"
      env:
        SNOWFLAKE_ACCOUNT: ${{ env.SNOWFLAKE_ACCOUNT }}
		
