on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Determine Branch Name
      id: branch_name
      run: |
        echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Set Environment Variables
      shell: bash
      run: |
        if [ "$BRANCH_NAME" == "dev" ]; then
            SNOWSQL_ACCOUNT= ${{ secrets.SNOWFLAKE_ACCOUNT_PROD }}
            SNOWSQL_USER=  ${{ secrets.SNOWFLAKE_USER_PROD }}
            SNOWSQL_PWD=  ${{ secrets.SNOWFLAKE_PASSWORD_PROD }}                    
        elif [ "$BRANCH_NAME" == "qa" ]; then
            SNOWSQL_ACCOUNT= ${{ secrets.SNOWFLAKE_ACCOUNT_PROD }}
            SNOWSQL_USER=  ${{ secrets.SNOWFLAKE_USER_PROD }}
            SNOWSQL_PWD=  ${{ secrets.SNOWFLAKE_PASSWORD_PROD }}                    
        elif [ "$BRANCH_NAME" == "main" ]; then
            SNOWSQL_ACCOUNT= ${{ secrets.SNOWFLAKE_ACCOUNT_PROD }}
            SNOWSQL_USER=  ${{ secrets.SNOWFLAKE_USER_PROD }}
            SNOWSQL_PWD=  ${{ secrets.SNOWFLAKE_PASSWORD_PROD }}                    
        fi
        
    - name: Debug Snowflake Account
      run: |
        echo "SNOWFLAKE_ACCOUNT=$SNOWSQL_ACCOUNT"
