on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Determine Branch Name
      id: branch_name
      run: |
        echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Set Environment Variables
      shell: bash
      run: |
        if [ "$BRANCH_NAME" == "dev" ]; then
            echo "SNOWFLAKE_ACCOUNT=" >> $GITHUB_ENV
        elif [ "$BRANCH_NAME" == "qa" ]; then
            echo "SNOWFLAKE_ACCOUNT=" >> $GITHUB_ENV
        elif [ "$BRANCH_NAME" == "main" ]; then
            echo "SNOWFLAKE_ACCOUNT=" >> $GITHUB_ENV
        fi
        
    - name: Debug Snowflake Account
      run: |
        echo "SNOWFLAKE_ACCOUNT=$SNOWFLAKE_ACCOUNT"
