name: Snowflake CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - qa
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install SnowSQL
      run: |
        curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
        SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
        echo "~/snowflake" >> $GITHUB_PATH 
        
    - name: Set Environment Variables
      env:
        ENV: ${{ github.ref_name }}
      run: |
        if [ "$ENV" == "dev" ]; then
          echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT_DEV }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER_DEV }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD_DEV }}" >> $GITHUB_ENV
        elif [ "$ENV" == "qa" ]; then
          echo "SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT_QA }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_USER=${{ secrets.SNOWFLAKE_USER_QA }}" >> $GITHUB_ENV
          echo "SNOWFLAKE_PASSWORD=${{ secrets.SNOWFLAKE_PASSWORD_QA }}" >> $GITHUB_ENV
        elif [ "$ENV" == "main" ]; then  
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_PROD }}
          SNOWSQL_USER:  ${{ secrets.SNOWFLAKE_USER_PROD }}
          SNOWSQL_PWD:  ${{ secrets.SNOWFLAKE_PASSWORD_PROD }}        
        fi


    - name: Configure SnowSQL
      env:
        SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT_PROD }}
        SNOWSQL_USER:  ${{ secrets.SNOWFLAKE_USER_PROD }}
        SNOWSQL_PWD:  ${{ secrets.SNOWFLAKE_PASSWORD_PROD }}
      run: |
        mkdir -p ~/.snowsql
        cat > ~/.snowsql/config << EOF
        [connections]
        accountname = SNOWSQL_ACCOUNT
        username = SNOWSQL_USER
        password = SNOWSQL_PWD
        role = ACCOUNTADMIN
        EOF
        chmod 600 ~/.snowsql/config


    - name: Verify SnowSQL installation
      run: snowsql -v  

    - name: Run SnowSQL show db Command
      run: snowsql -q "SHOW DATABASES;"   


    - name: Execute SQL Scripts
      run: |
        for file in ./scripts/*.sql; do
          echo "Executing $file"
          snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD -f $file
        done

    - name: Run Test Queries
      run: |
        for test in ./test/*.sql; do
          echo "Running test $test"
          snowsql -a $SNOWFLAKE_ACCOUNT -u $SNOWFLAKE_USER -p $SNOWFLAKE_PASSWORD -f $test > test_output.txt
          grep "FAILED" test_output.txt && exit 1 || echo "Test passed"
        done

    - name: Promote Code to qa
      if: success() && github.ref_name == 'dev'
      run: |
        echo "Promoting code to qa..."
        git checkout qa
        git merge dev
        git push origin qa

    - name: Promote Code to main
      if: success() && github.ref_name == 'qa'
      run: |
        echo "Promoting code to main..."
        git checkout main
        git merge qa
        git push origin main
